#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

INPUT_FILE=$1
START_LINE=`head -n1 $INPUT_FILE`
PATTERN="\#[0-9]+:.?(.*)"

if ! [[ "$START_LINE" =~ $PATTERN ]]; then
  echo "Bad commit message, see example: #taskId: commit message" 
  exit 1
fi
